import type { Meta, StoryObj } from '@storybook/angular';

import { IconComponent } from './icon.component';

const meta: Meta<IconComponent> = {
  title: 'UI/Icon',
  component: IconComponent,
  tags: ['autodocs'],
  argTypes: {
    iconName: {
      options: [
        'cookie-bite',
        'arrow-trend-down',
        'rss',
        'feed',
        'face-monocle',
        'draw-polygon',
        'scale-balanced',
        'balance-scale',
        'calendar-lines',
        'calendar-note',
        'arrow-down-big-small',
        'sort-size-down',
        'gauge-simple-high',
        'tachometer',
        'tachometer-fast',
        'do-not-enter',
        'shower',
        'dice-d8',
        'desktop',
        'desktop-alt',
        'm',
        'spinner-scale',
        'grip-dots-vertical',
        'face-viewfinder',
        'soft-serve',
        'creemee',
        'h5',
        'hand-back-point-down',
        'table-list',
        'th-list',
        'basket-shopping-minus',
        'comment-sms',
        'sms',
        'rectangle',
        'rectangle-landscape',
        'clipboard-list-check',
        'turkey',
        'book',
        'user-plus',
        'ice-skate',
        'check',
        'battery-three-quarters',
        'battery4',
        'tomato',
        'sword-laser',
        'house-circle-check',
        'buildings',
        'angle-left',
        'cart-flatbed-boxes',
        'dolly-flatbed-alt',
        'diagram-successor',
        'truck-arrow-right',
        'square-w',
        'arrows-split-up-and-left',
        'lamp',
        'airplay',
        'hand-fist',
        'fist-raised',
        'shield-quartered',
        'slash-forward',
        'location-pen',
        'map-marker-edit',
        'cloud-moon',
        'pot-food',
        'briefcase',
        'person-falling',
        'image-portrait',
        'portrait',
        'user-tag',
        'rug',
        'print-slash',
        'earth-europe',
        'globe-europe',
        'cart-flatbed-suitcase',
        'luggage-cart',
        'hand-back-point-ribbon',
        'rectangle-xmark',
        'rectangle-times',
        'times-rectangle',
        'window-close',
        'tire-rugged',
        'lightbulb-dollar',
        'cowbell',
        'baht-sign',
        'corner',
        'chevrons-right',
        'chevron-double-right',
        'book-open',
        'book-journal-whills',
        'journal-whills',
        'inhaler',
        'handcuffs',
        'snake',
        'triangle-exclamation',
        'exclamation-triangle',
        'warning',
        'note-medical',
        'database',
        'down-left',
        'share',
        'mail-forward',
        'face-thinking',
        'turn-down-right',
        'bottle-droplet',
        'mask-face',
        'hill-rockslide',
        'scanner-keyboard',
        'circle-o',
        'grid-horizontal',
        'message-dollar',
        'comment-alt-dollar',
        'right-left',
        'exchange-alt',
        'columns-3',
        'paper-plane',
        'road-circle-exclamation',
        'dungeon',
        'hand-holding-box',
        'input-text',
        'window-flip',
        'window-alt',
        'align-right',
        'scanner-gun',
        'scanner',
        'tire',
        'engine',
        'money-bill-1-wave',
        'money-bill-wave-alt',
        'life-ring',
        'hands',
        'sign-language',
        'signing',
        'circle-caret-right',
        'caret-circle-right',
        'turn-left',
        'wheat',
        'file-spreadsheet',
        'audio-description-slash',
        'bell-ring',
        'calendar-day',
        'water-ladder',
        'ladder-water',
        'swimming-pool',
        'arrows-up-down',
        'arrows-v',
        'chess-pawn-piece',
        'chess-pawn-alt',
        'face-grimace',
        'grimace',
      ],
      control: { type: 'select' }, // Automatically inferred when 'options' is defined
    },
  },
};

export const Default: StoryObj<IconComponent> = {
  args: {
    iconName: 'coffee',
  },
};

export default meta;
